### ISSUE TITLE
Follow symfony nginx virtualhost

### ISSUE THREAD

**Issue by amenophis** [ElaoLegacy/ansible-role-projects#5]
Why the virtualhost template (https://github.com/Elao/ansible-role-projects/blob/master/templates/symfony/project_v2.j2) does not follow the exemple in the symfony documentation (http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx) ?

Got a problem with the main rewrite directive when i use the following configuration:
Client -> ReverseProxy (nginx:80) -> AppServer (nginx:8080). 

If i call http://my-app.com/app.php, i am redirected to http://my-app.com:8080/

All works well with symfony provided documentation.

Do you want me I submit a PR to use the symfony virtualhost configuration ?

**Comment by nervo** [comment]
We have followed the nginx way: http://wiki.nginx.org/Symfony

Let's find if we can merge both of them...
